name: fleetime_quiz
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flex_color_scheme: ^7.0.4
  flutter:
    sdk: flutter
  flutter_form_builder: ^8.0.0
  google_fonts: ^4.0.4
  responsive_framework: ^1.0.0
  scaffold_gradient_background: ^1.0.3+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
